language: java
sudo: required
services:
- docker
jdk:
- openjdk8
branches:
  only:
  - master
  - develop
  - feature-travis
os:
- linux
install: true
script: mvn -q clean install
before_deploy:
- bash ./.ci/before_deploy.sh
deploy:
  provider: script
  script: bash ./.ci/deploy.sh
  on:
    branch: master
    tags: true
cache:
  directories:
  - "$HOME/.m2"
notifications:
  email: dev-notify@lockss.org
before_install:
- openssl aes-256-cbc -K $encrypted_4effbd4536cc_key -iv $encrypted_4effbd4536cc_iv
  -in .ci/codesigning.asc.enc -out .ci/codesigning.asc -d
env:
  global:
  - secure: tUg4sos52jbVlj8Cg0r1vr2diJZRPsP5LUlsGSbLhetdV62ajnYKTNKoDURMgax0RRaD8/pVBhfmMCJ90b/O2RoKFYrzN6lBk+eymTr+hDgjrhNKSTylg3OSn/sGHMHvM1sdAv+jJgN2v3t8FzxCnQubLNuJMPPWr7qvW2nrkYJG0HUhR4E7k1gvIkZT35ommXIMm6+w7Bp0T0cFSJ9vAxp3ZIvaJozHGfFFZUG35iC8r2SUVyvhCwop2Gdb3abdHBgcD5cDPc7d33KAzSe0zB1vSf5+/yZUsLH/7T1Kpu0IIaaKhkRxb7oQHGw56ov60Oswn50u+0kB1psFrhI+or4E/UeyXUjt7uGw35bGkgLrdJ0TKSULocHLUhX7/GpmsRnoF9gfSMsPZt5Djf2S3l6FNuftQWyP7aQjIxcvm3g503/pk1ZaL1Yp5tmlgU3LT1J5hjS2v5RZXwkFqNq0wwFKYoRnKKxTCFOGcFT1cCMEZh+97ZLc5PBJNm7eOfFope3NANhVUeNQ/hyjoCu1suXK8YWaCPK2HY/CBR3IySpmWffsolZbkUDkxk43XKGk3FHzRSWuatSdJwKpC/HL/0huVeM+x0ct+V7TJ7NKwCqUF8BTZ22XyhbXzq0/9VkeZRwwuCbweyk/t65o46OFuodUUYJKwMrd7D8qo9jTccI=
  - secure: YTvR72xYeBAWFOe4b2LCXaQop5eLi3jOn8PG/KYa4toSmXKL01kzI60mWsC5ILg9veSC5RVLXB7wJBT+PbXuOjFNUakqDSumGDqzhiW94h6Gtlkw7DdXxgtB0qs5NFOfEcR85lHg3QaDzIZFYs1dwjE1UZcLeK3FCyR2d7kMwvVCTEzMUYZNUccVShwI2A4+IwOPhzDrnXLt4T52cj9HYLMxiDwv4bm2fl4VG8Jw6KSH+KzanY+uv2UCVsOlkTH5pVHbY3s8nr2gXhcKFAJuPB/4A8FhtmNFp9w23BcSeZPxJ8B7FaFRMqFIFA69JE6ViwAfzUkXmE3VwDY+bH/SlDXNorW84lKZFX3+VVmt5Bjx9v9c1qQugQ9Whq6cbYewJg8DdAGLZZcI4qGFWr2rsPu5o+KpahYKscEDIZSSaj/ISkUAggjedCxNufisHmak5hGFdebMM9lUnbPwT7GjyougPOWahSn7IOKrzFj+VZNwUYJ34wyulBFaOgoyZKdJbrMbl/QaZ8m4rzy53E/DVPcKsEwaD2dSDPNqSZ62WkLG8GnVePm5f3gmMUFsi9Mwz3nq9+SDWBkoEVP5WprrhSqSbcjl6Jw2qSbwkbj21Gv6fMkpDOkoYVperc1ddTqp/XdUhwcvb1oHmJq5SSul7N5CmcwDHzHR1pzcax34Z14=
  - secure: bIyuspLVCr2yY4NWueLpCKWaa3U+lcCRO/f9OV1slsMZE0sRIfsMNu4gBmtTFkdJ3J58wTEDyO7sTyg0JjHhxI9WMMEvbe3x+8w/DPTeDe758Q++zAoa0sbmtDTWGd426eZzl1x7kOR22Ai6GHZEWSnSVouQAbKyOaVZwlFDh1q+XtL7AJyeIMYgbgqe6ZptgVLxQwbxXH5kvcVB/4ljf9oLLSegMIeYMfr8cvWMGi9ljOmMM60JC7C93EZTkmVVN5A7lJ4vsS7vRxaHkK4akfiHRV7E4BpTwWtdgaPji910JNMUYhd4WxpOd85Ht6h+L6h1WaVf/1UZEdd5orCT7t2SiBKfSgd0VRIqAt5YtWNnGQ1bJscPl0ImnlCHNThNQBps/fpe6a7UNzG0/kRXblYc0q8UsWSRAVy/dp2J57s/+hPnr09DGlbmmYzgrQmQkYvkawQ7zOSDtJsfcBH4xl84jZil4TrcswkmEDWCMYEoe/MD0zEVikjiy/3SZxGUeE1pZgXg6/GTrGFro69FXMHW5Y1z15xv6hb8VhbI9QA5fWrSJfJmA5nncL0rQT2PpIud/Gy1viXCN82BE/6BeqP1h5S6FBAPARaJh55w7dKqiW4igMZkZnZHrFXsHORpGwkXYE+xesk6lt+RZ9+X+ZHPee5ANNwSF9Nrk/nMWio=
  - secure: NjdIH1jqiTKmznJO/T2fn5u0hMUds3dKE6PlQ6O+39jpiqHwdEUjivNAI083c1XDhahvOlGg0+h69kdqwMfuy60cn9pnM7IWHFb4FcJ+7wUh/HeFO4dNjCXf13Kkkn01aAQUEuy4Qby5qLAnlIUMCf3+dxAlmWBy4hne+hYWrLwkpUJXGk54QzRoCwIQ4gO9pjguJpGKI+Unk7l7xWKFeZsmduP9pMuzSktieWjRoFIhKA2IuXwNfCyKe30ZbfnZNRtTMGxAteR2vnW2lohVWQBCImbK/WhDy4I5ghajLntnzGcsF3CdOJZYjslrCHD5cmc9XkZ+GpD7nV61w1IxqGfDkJK3ikMD9O5OPso4HBe4WA9E+tULMtTDwvrxKHLY7LpGOIr0z5iGIJIfXM5N6Hns7zIdcH1rDDfb0GCvQ7T9G0tbPpXIREAJb2zCB6/02sKYJPEXfzz5pGQ0OTiKOpBiJtymCRaRG8KwHfyAj92lzynyzdAbq9hSMsQ/LiZ0sr3ymnNzlAaAKWTe/Sxkvl4dMDTOwPMt/YzWdAsE9/RI3cNZhA3LhS7ddrxKaTBaCxBLrtkIuuVmZQ9aneF8kVoAKMjDgD/lNf6XfNBIIsTOTT4/aj/aPWAMNl76emsNVNPMm5y5zrHvHK2NYOtMkWN/drpd4RX7c1mbcM1M9HM=
  - secure: kjm4FSz/E3HcUXeEMID0S0gwsqydKrFymBWd163WxXjRS69yfXfYMmfLdy1AjzQ0Kj/wfsS4rhxQsLJA1NbRqwUKFG8pXlVMAKSgGuyxD9WsVLQQE2Q4tvTnUi76IxmQ0t9UEq+c9JjQM4GtK7BDbHeT90NMDgoaqf2YzJ7YQcfV1oYMIWDgEXOtIS513am1kOo+wwf6VMp/hGSOUQMyFxehGvjSfMoYOB1FfeyNfC65A9k6+/2PddK4vKteDbYWjCaBoUAirS78csl8+D6Ptlf//MTQfgax3ei6pCMlLPjBQIUtJBep66GwGfuNAQOy4MHm37YEX9Rkui7S/P1Tc8xX2N0mbNUN9uuRSTKOHmnz85WFV9uVOpcIDF0nnIANa8M6awgEzX6WJo5tSs45Ay0gfRegfH7XRHiUnvr8YGQ+DxSz3fFvGmdKFwYKliZLWwFYG98Moscye9PnEIxu21EEo98YZVBZaKkjIOrECxw2w9DaTQfY/+3dfhlqDpJ7nv6Ek1t0rBFaIdaqTGQCu/wLsuuvLwJMPwMi6Rwd3aPznvGTDoRZ8zQYnjJqe3SrDcAuf0kVYNZ/4lvd32QSldZkNJslzy4oNFI5KswYrH53EGJoXfco9A8l8m//XSFO5hd6XPbv4yYNXIvzjSP/kZUAVmR9ZEcEM/F3aNvfAnM=
  - secure: oby+JC0rat67wCsU8k7tso+GYnyU6dU3sjZSYDCJHaw5fe6qD9DKLH3IkvCWY1yx2OiMb0/LiMQrDoUEJOh/DzkIThMhDxNFTQ39b8MOS3v6c2LesLxmuHViQYoR0JW8L++Q68pml3vbe/JtJomPMCfUF+3lnfc8aGMxMKSAINWEhmO39n63NjVEJcKRu12LLc3nn9qrFEvJKxg4aGVrY8G8PFqsjqcspU0fO8J4cQ+YQKf45u11GO9MvhIc3G9tDafRkE5sVesiyNsQle8UVH4MPwF8UnYvvV96dZjaocqjhVoFu5aISzH8KuwIpYCXJnlyLVFP1gxEtUhRZLOvpNFkPKZLO5YX9hnPl/hxuwjCFvCGXL8dVj11FuTrPErvGOiY+rNDaWIF+fPPYhBuAshbnOVW85MkcP6V+X06rgsjVZk1cctlscxyFVdwEOKMIZKtlkaRIxG510bKHWMg+UdpyoEgN2pzkmleFNgdJgD2SGnC+JHtz9WF1QYX/QK5epmYtJxnjpeG0AARnbv0Pj1K5DYXWBIlvKKpXJqrL+HcQSmBof94tQsUvnbURQezNvM5mmvJzdSuytKl2AP6Uz9MhbxzpQpsNm/EoP7QJJzXUuPliRPrMJmULAR2vrhNb88zdEFZRhKfX4S+K8RlnJI6V8nk/QFNe3+dTzSxR68=
